### ISSUE TITLE
支持不同的 MAA 组件

### ISSUE THREAD

**Issue by ChingCdesu** [MaaAssistantArknights/MaaDownloadServer#1]
考虑到未来maa核心和ui的迭代进度会不一致，且ui形式多样(WPF, electron, web...)
例如：
core version: v2.8.0
electron app version: v1.0.0

**Comment by AlisaAkiron** [comment]
emmm...设计时只考虑了Core，没有考虑其他组件，要加入也可以，就是 API 会有些许变化
